version: "3.8"
services:
  server:
    build: ./server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./server:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: go run main.go
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "8080:8080"

  supertest:
    build: ./supertest
    environment:
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    volumes:
      - ./supertest/app.test.js:/home/node/supertest/app.test.js
      - ./supertest/package.json:/home/node/supertest/package.json
      - ./supertest/jest.config.js:/home/node/supertest/jest.config.js
    working_dir: /home/node/test
    command: npx jest --runInBand
    depends_on:
      - postgres
      - redis
      - server
    links:
      - postgres
      - redis
      - server

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

    # access to the redis CLI:
    # $> docker-compose exec redis sh -c 'redis-cli -h redis'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}         # psql
      PGPASSWORD: ${PGPASSWORD} # psql
      PGDATABASE: ${PGDATABASE} # psql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    # access to the psql CLI (to fizzbuzz database):
    # $> docker-compose exec postgres psql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    links:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  redis-data:
    driver: local
